### PR TITLE
Use the new csproj format (for VS2017/2019)

### PR DESCRIPTION
**Pull request by ghost**
This will make migrating to .NET Core 3 easier and has the benefit of making the project files more readable. This was done with the [tool](https://github.com/hvanbakel/CsprojToVs2017) that Microsoft recommended and everything seems to work perfectly.

### CODE REVIEW

**Comment by ghost** [comment]
It looks like sonar is blocking appveyor from completing the build.

**Comment by ghost** [comment]
https://medium.com/@stef.heyenrath/how-to-fix-sonarcloud-issue-in-a-github-pr-when-using-appveyor-integration-8909b49406b4 has a fix for this.

**Comment by jackpoz** [comment]
do recent versions of VS handle this conversion automatically too ?

**Comment by ghost** [comment]
VS2017/2019 do not convert to the new csproj format because both the old and new formats are supported. New projects are made with this csproj format and when moving to .NET Core 3 this format will be necessary.

**Comment by jackpoz** [comment]
Just as a tip, please create a different branch when opening a PR, it's easier for the maintainer to check it out locally

**Comment by jackpoz** [comment]
Does the layout of the "bin" folder change with the new project format ? I see there is a subfolder "net46" now (bin\Debug\net46), same applies to plugins (bin\Debug\plugins\net46).
This means the folder structure has to be manually modified for the plugins folder to be in the same folder as OnlineRadio.GUI.exe

**Comment by jackpoz** [comment]
I "fixed" AppVeyor build by running SonarCube only if it's not a PR

**Comment by ghost** [comment]
@jackpoz that is the new folder structure now in order to support targeting multiple frameworks (so someone can target net46 while simultaneously targeting  .net core 3).

**Comment by jackpoz** [comment]
Is it possible to change https://github.com/jackpoz/OnlineRadio/pull/9/files#diff-e5d128c1d02bcb414bce42baf92dc461R9 so that the structure will look like this, with "plugins" directory in the same folder as the GUI executable ?
- bin
  - Debug
    - net46
      - OnlineRadio.GUI.exe
      - plugins
        - LyricsPlugin.dll

**Comment by ghost** [comment]
yes, that should be possible.

**Comment by jackpoz** [comment]
could you try changing the build output path of plugins to be in the same folder as OnlineRadio.GUI.exe ?

**Comment by jackpoz** [comment]
Replaced by https://github.com/jackpoz/OnlineRadio/pull/12

**Pull request closed without merging**
